### ISSUE TITLE
build system does not work

### ISSUE THREAD

**Issue by vanhauser-thc** [google/fuzzbench#1049]
the last three experiment all failed to build, e.g. from the newest, 2020-01-22-aflpp:

```
$ gs://fuzzbench-data/2021-01-21-aflpp/build-logs/benchmark-zlib_zlib_uncompress_fuzzer-fuzzer-aflplusplus_cmplog_v3.txt
...
Step #3 - "aflplusplus_cmplog_v3-zlib_zlib_uncompress_fuzzer-builder": #19 [stage-1 12/12] RUN PYTHONPATH=/src python3 -u -c "from fuzzers import u...
Step #3 - "aflplusplus_cmplog_v3-zlib_zlib_uncompress_fuzzer-builder": #19 0.480 FUZZ_TARGET = zlib_uncompress_fuzzer
Step #3 - "aflplusplus_cmplog_v3-zlib_zlib_uncompress_fuzzer-builder": #19 0.480 CFLAGS = -pthread -Wl,--no-as-needed -Wl,-ldl -Wl,-lm -Wno-unused-command-line-argument -O3
Step #3 - "aflplusplus_cmplog_v3-zlib_zlib_uncompress_fuzzer-builder": #19 0.480 CXXFLAGS = -pthread -Wl,--no-as-needed -Wl,-ldl -Wl,-lm -Wno-unused-command-line-argument -stdlib=libc++ -O3
Step #3 - "aflplusplus_cmplog_v3-zlib_zlib_uncompress_fuzzer-builder": #19 0.483 Traceback (most recent call last):
Step #3 - "aflplusplus_cmplog_v3-zlib_zlib_uncompress_fuzzer-builder": #19 0.483   File "<string>", line 1, in <module>
Step #3 - "aflplusplus_cmplog_v3-zlib_zlib_uncompress_fuzzer-builder": #19 0.483   File "/src/fuzzers/aflplusplus_cmplog_v3/fuzzer.py", line 23, in <module>
Step #3 - "aflplusplus_cmplog_v3-zlib_zlib_uncompress_fuzzer-builder": #19 0.483     from fuzzers.aflplusplus import fuzzer as aflplusplus_fuzzer
Step #3 - "aflplusplus_cmplog_v3-zlib_zlib_uncompress_fuzzer-builder": #19 0.483   File "/src/fuzzers/aflplusplus/fuzzer.py", line 194
Step #3 - "aflplusplus_cmplog_v3-zlib_zlib_uncompress_fuzzer-builder": #19 0.483     if (not flags or (not '-l' in flags and not '-R' in flags)) and
Step #3 - "aflplusplus_cmplog_v3-zlib_zlib_uncompress_fuzzer-builder": #19 0.483                                                                   ^
Step #3 - "aflplusplus_cmplog_v3-zlib_zlib_uncompress_fuzzer-builder": #19 0.483 SyntaxError: invalid syntax
Step #3 - "aflplusplus_cmplog_v3-zlib_zlib_uncompress_fuzzer-builder": #19 ERROR: executor failed running [/bin/sh -c PYTHONPATH=$SRC python3 -u -c "from fuzzers import utils; utils.initialize_env(); from fuzzers.$FUZZER import fuzzer; fuzzer.build()"]: runc did not terminate sucessfully
Step #3 - "aflplusplus_cmplog_v3-zlib_zlib_uncompress_fuzzer-builder": ------
Step #3 - "aflplusplus_cmplog_v3-zlib_zlib_uncompress_fuzzer-builder":  > [stage-1 12/12] RUN PYTHONPATH=/src python3 -u -c "from fuzzers import utils; utils.initialize_env(); from fuzzers.aflplusplus_cmplog_v3 import fuzzer; fuzzer.build()":
Step #3 - "aflplusplus_cmplog_v3-zlib_zlib_uncompress_fuzzer-builder": ------
Step #3 - "aflplusplus_cmplog_v3-zlib_zlib_uncompress_fuzzer-builder": failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c PYTHONPATH=$SRC python3 -u -c "from fuzzers import utils; utils.initialize_env(); from fuzzers.$FUZZER import fuzzer; fuzzer.build()"]: runc did not terminate sucessfully
Finished Step #3 - "aflplusplus_cmplog_v3-zlib_zlib_uncompress_fuzzer-builder"
ERROR
ERROR: build step 3 "docker:19.03.12" failed: step exited with non-zero status: 1
ERROR: (gcloud.builds.submit) build e6d2df01-9835-40d7-b201-210917343f8b completed with status "FAILURE"
```

it builds and runs fine for me:
```
make test-run-aflplusplus_cmplog_v3-zlib_zlib_uncompress_fuzzer
...
gcr.io/fuzzbench/runners/aflplusplus_cmplog_v3/zlib_zlib_uncompress_fuzzer
INFO:root:Doing trial as part of experiment.
INFO:root:Starting trial.
Creating a fake seed file in empty corpus directory.
[run_afl_fuzz] Running target with afl-fuzz
[run_afl_fuzz] Running command: ./afl-fuzz -i /out/seeds -o /out/corpus -m none -t 1000+ -d -l 3 -p fast -c /out/cmplog/zlib_uncompress_fuzzer -- /out/zlib_uncompress_fuzzer 2147483647
[+] Loaded environment variable AFL_SKIP_CPUFREQ with value 1
[...]
[*] Fuzzing test case #226 (241 total, 0 uniq crashes found, perf_score=450, exec_us=31, hits=1, map=107)...
INFO:root:Doing final sync.
```

**Comment by inferno-chromium** [comment]
Is this the right file, i see 2021-01-22-aflpp running fine, see https://storage.googleapis.com/fuzzbench-data/2021-01-22-aflpp/build-logs/benchmark-zlib_zlib_uncompress_fuzzer-fuzzer-aflplusplus_cmplog_v3.txt
experiment just started, might have to wait an hour or two to see results.

**Comment by vanhauser-thc** [comment]
I just repeated the following command: `gsutil cat gs://fuzzbench-data/2021-01-21-aflpp/build-logs/benchmark-zlib_zlib_uncompress_fuzzer-fuzzer-aflplusplus_cmplog_v3.txt` and still see that error I posted on the bottom.
that is so weird.

**Comment by inferno-chromium** [comment]
> I just repeated the following command: `gsutil cat gs://fuzzbench-data/2021-01-21-aflpp/build-logs/benchmark-zlib_zlib_uncompress_fuzzer-fuzzer-aflplusplus_cmplog_v3.txt` and still see that error I posted on the bottom.
> that is so weird.

Sir, you are looking at the wrong date, need 01-22 instead of 01-21. Your report is coming out fine, see https://www.fuzzbench.com/reports/experimental/2021-01-22-aflpp/index.html. Need some sleep :)

**Comment by vanhauser-thc** [comment]
oh man ... yes... sorry. good night
