### ISSUE TITLE
aflplusplus fuzzer failures

### ISSUE THREAD

**Issue by inferno-chromium** [google/fuzzbench#1073]
Failure like 

1. "make test-run-aflplusplus_optimal-libhevc_hevc_dec_fuzzer", 
2. "make test-run-aflplusplus_optimal-freetype2-2017" 

are legit and show locally as well [@vanhauser-thc fyi]
There are others at https://github.com/google/fuzzbench/actions/runs/536892982, please do take time to reproduce locally. I am guessing all of this came after using clang-12 package. Can we try building with clang available in base-builder, that should be 12 as well.

**Comment by inferno-chromium** [comment]
Locally this one
3. make test-run-aflplusplus_v300c-freetype2-2017 fails with
```
#19 2.381 configure: error: C compiler cannot create executables
#19 2.381 See `config.log' for more details
#19 2.513 Traceback (most recent call last):
#19 2.513   File "<string>", line 1, in <module>
#19 2.513   File "/src/fuzzers/aflplusplus_v300c/fuzzer.py", line 30, in build
#19 2.513     aflplusplus_fuzzer.build("tracepc", "cmplog", "dict2file")
#19 2.513   File "/src/fuzzers/aflplusplus/fuzzer.py", line 147, in build
#19 2.513     utils.build_benchmark()
#19 2.513   File "/src/fuzzers/utils.py", line 76, in build_benchmark
#19 2.513     subprocess.check_call(['/bin/bash', '-ex', build_script], env=env)
#19 2.513   File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
#19 2.513     raise CalledProcessError(retcode, cmd)
#19 2.513 subprocess.CalledProcessError: Command '['/bin/bash', '-ex', '/src/build.sh']' returned non-zero exit status 77.
```

**Comment by inferno-chromium** [comment]
Locally this one reproduces as well
4. make test-run-aflplusplus_cmplog_transform-libhevc_hevc_dec_fuzzer
```
[*] Fuzzing test case #0 (1 total, 0 uniq crashes found, perf_score=100, exec_us=5028, hits=0, map=1490)...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/src/fuzzers/aflplusplus_cmplog_transform/fuzzer.py", line 35, in fuzz
    aflplusplus_fuzzer.fuzz(input_corpus,
  File "/src/fuzzers/aflplusplus/fuzzer.py", line 208, in fuzz
    afl_fuzzer.run_afl_fuzz(input_corpus,
  File "/src/fuzzers/afl/fuzzer.py", line 131, in run_afl_fuzz
    subprocess.check_call(command, stdout=output_stream, stderr=output_stream)
  File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./afl-fuzz', '-i', '/out/seeds', '-o', '/out/corpus', '-m', 'none', '-t', '1000+', '-d', '-l', '2', '-x', './afl++.dict', '-c', '/out/cmplog/hevc_dec_fuzzer', '-p', 'fast', '-x', '/out/hevc_dec_fuzzer.dict', '--', '/out/hevc_dec_fuzzer', '2147483647']' died with <Signals.SIGSEGV: 11>.
ERROR:root:Executed command: "nice -n 5 python3 -u -c from fuzzers.aflplusplus_cmplog_transform import fuzzer; fuzzer.fuzz('/out/seeds', '/out/corpus', '/out/hevc_dec_fuzzer')" returned: 1.
ERROR:root:Fuzz process returned nonzero. Extras: {'traceback': 'Traceback (most recent call last):\n  File "/src/experiment/runner.py", line 209, in run_fuzzer\n    new_process.execute(command,\n  File "/src/common/new_process.py", line 124, in execute\n    raise subprocess.CalledProcessError(retcode, command)\nsubprocess.CalledProcessError: Command \'[\'nice\', \'-n\', \'5\', \'python3\', \'-u\', \'-c\', "from fuzzers.aflplusplus_cmplog_transform import fuzzer; fuzzer.fuzz(\'/out/seeds\', \'/out/corpus\', \'/out/hevc_dec_fuzzer\')"]\' returned non-zero exit status 1.\n'}
INFO:root:Doing final sync.
make: *** [docker/generated.mk:104886: test-run-aflplusplus_cmplog_transform-libhevc_hevc_dec_fuzzer] Error 1
```

**Comment by vanhauser-thc** [comment]
thanks, will look into this later tonight

**Comment by inferno-chromium** [comment]
Thanks @vanhauser-thc , looks like finally these are starting to reproduce locally, so nice. Take your time, no rush, if that gets fixed, it will simplify both of our lives on CI and faster experiments.

make test-run-aflplusplus_introspection2-libpcap_fuzz_both
```
[*] Fuzzing test case #0 (1 total, 0 uniq crashes found, perf_score=100, exec_us=165, hits=0, map=4)...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/src/fuzzers/aflplusplus_introspection2/fuzzer.py", line 35, in fuzz
    aflplusplus_fuzzer.fuzz(input_corpus,
  File "/src/fuzzers/aflplusplus/fuzzer.py", line 208, in fuzz
    afl_fuzzer.run_afl_fuzz(input_corpus,
  File "/src/fuzzers/afl/fuzzer.py", line 131, in run_afl_fuzz
    subprocess.check_call(command, stdout=output_stream, stderr=output_stream)
  File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./afl-fuzz', '-i', '/out/seeds', '-o', '/out/corpus', '-m', 'none', '-t', '1000+', '-d', '-p', 'coe', '-x', './afl++.dict', '--', '/out/fuzz_both', '2147483647']' died with <Signals.SIGSEGV: 11>.
ERROR:root:Executed command: "nice -n 5 python3 -u -c from fuzzers.aflplusplus_introspection2 import fuzzer; fuzzer.fuzz('/out/seeds', '/out/corpus', '/out/fuzz_both')" returned: 1.
ERROR:root:Fuzz process returned nonzero. Extras: {'traceback': 'Traceback (most recent call last):\n  File "/src/experiment/runner.py", line 209, in run_fuzzer\n    new_process.execute(command,\n  File "/src/common/new_process.py", line 124, in execute\n    raise subprocess.CalledProcessError(retcode, command)\nsubprocess.CalledProcessError: Command \'[\'nice\', \'-n\', \'5\', \'python3\', \'-u\', \'-c\', "from fuzzers.aflplusplus_introspection2 import fuzzer; fuzzer.fuzz(\'/out/seeds\', \'/out/corpus\', \'/out/fuzz_both\')"]\' returned non-zero exit status 1.\n'}
INFO:root:Doing final sync.
make: *** [docker/generated.mk:15114: test-run-aflplusplus_introspection2-libpcap_fuzz_both] Error 1
```

**Comment by vanhauser-thc** [comment]
>     1. "make test-run-aflplusplus_optimal-libhevc_hevc_dec_fuzzer",

succeeds for me locally. was the issue with the changed llvm-12 repo?
```
make test-run-aflplusplus_optimal-libhevc_hevc_dec_fuzzer
...
[*] Entering queue cycle 1.
[*] Fuzzing test case #0 (1 total, 0 uniq crashes found, perf_score=100, exec_us=2318, hits=0, map=606)...
INFO:root:Doing final sync.
```

>     2. "make test-run-aflplusplus_optimal-freetype2-2017"

that needed backporting a fox for a change in llvm 12

**Comment by inferno-chromium** [comment]
> make test-run-aflplusplus_optimal-libhevc_hevc_dec_fuzzer

i just retested this, with tip-of-tree trunk (no custom patches) and it crashes with that [maybe try pruning your local images with docker system prune -a]. i don't remember seeing this when we didn't have clang-12, since i did quite a bit of bug based benchmark experiments and it did work.

```
[*] Fuzzing test case #0 (1 total, 0 uniq crashes found, perf_score=100, exec_us=5006, hits=0, map=606)...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/src/fuzzers/aflplusplus_optimal/fuzzer.py", line 127, in fuzz
    aflplusplus_fuzzer.fuzz(input_corpus,
  File "/src/fuzzers/aflplusplus/fuzzer.py", line 208, in fuzz
    afl_fuzzer.run_afl_fuzz(input_corpus,
  File "/src/fuzzers/afl/fuzzer.py", line 131, in run_afl_fuzz
    subprocess.check_call(command, stdout=output_stream, stderr=output_stream)
  File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./afl-fuzz', '-i', '/out/seeds', '-o', '/out/corpus', '-m', 'none', '-t', '1000+', '-d', '-x', './afl++.dict', '-p', 'fast', '-x', '/out/hevc_dec_fuzzer.dict', '--', '/out/hevc_dec_fuzzer', '2147483647']' died with <Signals.SIGSEGV: 11>.
ERROR:root:Executed command: "nice -n 5 python3 -u -c from fuzzers.aflplusplus_optimal import fuzzer; fuzzer.fuzz('/out/seeds', '/out/corpus', '/out/hevc_dec_fuzzer')" returned: 1.
ERROR:root:Fuzz process returned nonzero. Extras: {'traceback': 'Traceback (most recent call last):\n  File "/src/experiment/runner.py", line 209, in run_fuzzer\n    new_process.execute(command,\n  File "/src/common/new_process.py", line 124, in execute\n    raise subprocess.CalledProcessError(retcode, command)\nsubprocess.CalledProcessError: Command \'[\'nice\', \'-n\', \'5\', \'python3\', \'-u\', \'-c\', "from fuzzers.aflplusplus_optimal import fuzzer; fuzzer.fuzz(\'/out/seeds\', \'/out/corpus\', \'/out/hevc_dec_fuzzer\')"]\' returned non-zero exit status 1.\n'}
INFO:root:Doing final sync.
make: *** [docker/generated.mk:115386: test-run-aflplusplus_optimal-libhevc_hevc_dec_fuzzer] Error 1
```

**Comment by vanhauser-thc** [comment]
> make test-run-aflplusplus_introspection2-libpcap_fuzz_both

works locally for me too:
```
make test-run-aflplusplus_introspection2-libpcap_fuzz_both
[...]
[*] Fuzzing test case #125 (138 total, 0 uniq crashes found, perf_score=300, exec_us=54, hits=3, map=119)...
INFO:root:Doing final sync.
```

**Comment by vanhauser-thc** [comment]
I have fixes for 2 + 3

**Comment by vanhauser-thc** [comment]
#1074

**Comment by inferno-chromium** [comment]
> I have fixes for 2 + 3

yes i think we have 2 kind of bugs, the freetype stuff that you have fix for and this mysterious ci failure that started reproducing for me locally [Signals.SIGSEGV: 11].

**Comment by vanhauser-thc** [comment]
i wiped all gcr.io docker containers and rebuilt test-run-aflplusplus_introspection2-libpcap_fuzz_both + test-run-aflplusplus_optimal-libhevc_hevc_dec_fuzzer from scratch - both work.

can you somehow keep the core file? e.g. in the python script when it detects the segfaults copy the core file out to the cloud or somewhere?

**Comment by inferno-chromium** [comment]
> i wiped all gcr.io docker containers and rebuilt test-run-aflplusplus_introspection2-libpcap_fuzz_both + test-run-aflplusplus_optimal-libhevc_hevc_dec_fuzzer from scratch - both work.
> 
> can you somehow keep the core file? e.g. in the python script when it detects the segfaults copy the core file out to the cloud or somewhere?

Something is up with core generation inside docker, still trying to figure that out, but here is gdb backtrace.

```
Program received signal SIGSEGV, Segmentation fault.
skim (current_end=0x7ffff6956920, current=0x7ffff6a7c000, 
    virgin=0x7ffff8099010) at include/coverage-64.h:22
22	include/coverage-64.h: No such file or directory.
#0  skim (current_end=0x7ffff6956920, current=0x7ffff6a7c000, 
    virgin=0x7ffff8099010) at include/coverage-64.h:22
#1  has_new_bits_unclassified (
    virgin_map=0x7ffff7f58010 "\376\337\337\376\376", '\377' <repeats 11 times>, "\376\377\377\376\376", '\377' <repeats 11 times>, "\376\377\376", '\377' <repeats 11 times>, "\376\377\377\376\377\377\376\377\376\377\376\377\376\377\376\377\376\375\375", '\377' <repeats 11 times>, "\375\377\373\377\377\367\377\377\377\367\377\377\377\367\377\377\377\367\377\377\377\367\377\377\377\367\377\377\377\367\377\377\377\367\377\377\377\367\373\377\377\375\377\377\377\375\377\377\377\375\377\377\377\375\377\377\377\375\377\377\377\375\377\377\377\375\377\377\377\375\377\377\377\375\375\377\377\377\375\375\377\375\375", '\377' <repeats 11 times>, "\375\377\375\377\377\377\375\375\377\377\377\375\377\377\377\375\377\377\377\375\377\377\377\375\377\377\377\375\377\377"..., 
    afl=0x7ffff7f99010) at src/afl-fuzz-bitmap.c:272
#2  save_if_interesting (afl=afl@entry=0x7ffff7f99010, 
    mem=mem@entry=0x6790b8, len=len@entry=2, fault=0 '\000')
    at src/afl-fuzz-bitmap.c:488
#3  0x000000000040d319 in common_fuzz_stuff (afl=0x7ffff7f99010, 
    out_buf=0x6790b8 "\213", <incomplete sequence \355>, len=2)
    at src/afl-fuzz-run.c:934
#4  0x000000000042dc1a in fuzz_one_original (afl=0x7ffff7f99010)
    at src/afl-fuzz-one.c:2659
#5  0x000000000040878e in fuzz_one (afl=<optimized out>)
    at src/afl-fuzz-one.c:5404
#6  main (argc=<optimized out>, argv_orig=<optimized out>, 
    envp=<optimized out>) at src/afl-fuzz.c:1918
```

**Comment by inferno-chromium** [comment]
[core.118.zip](https://github.com/google/fuzzbench/files/5928787/core.118.zip)

**Comment by vanhauser-thc** [comment]
will look at that tomorrow.
I just ran an asan enabed build - no issue detected. and it makes no sense to have an issue in that place.
can I download that specific docker image somewhere?

**Comment by inferno-chromium** [comment]
> will look at that tomorrow.
> I just ran an asan enabed build - no issue detected. and it makes no sense to have an issue in that place.
> can I download that specific docker image somewhere?

1. added core archive in last comment, see if that helps :(

2. image and command is this.
```
docker run \
--privileged --ulimit core=-1 --security-opt seccomp=unconfined \
--cpus=1 \
--cap-add SYS_NICE \
--cap-add SYS_PTRACE \
-e FUZZ_OUTSIDE_EXPERIMENT=1 \
-e FORCE_LOCAL=1 \
-e TRIAL_ID=1 \
-e FUZZER=aflplusplus_optimal \
-e BENCHMARK=libhevc_hevc_dec_fuzzer \
-e FUZZ_TARGET=hevc_dec_fuzzer \
-e MAX_TOTAL_TIME=20 \
-e SNAPSHOT_PERIOD=10 \
gcr.io/fuzzbench/runners/aflplusplus_optimal/libhevc_hevc_dec_fuzzer
```

**Comment by vanhauser-thc** [comment]
From which commit (fuzzbench or afl++) is that core? From the one I pushed today or the previous one?

**Comment by inferno-chromium** [comment]
> From which commit (fuzzbench or afl++) is that core? From the one I pushed today or the previous one?

This is with latest - 9377150b8275009bb13b5e78fd338910cc13c95c

**Comment by vanhauser-thc** [comment]
It looks like this is OOM that is not caught on startup. using an asan build on the CI to be sure. it would easily explain why everything is working for me locally.

**Comment by inferno-chromium** [comment]
> It looks like this is OOM that is not caught on startup. using an asan build on the CI to be sure. it would easily explain why everything is working for me locally.

this can happening in ci, but does not explain why i consistently hit it locally. if these 2 configs are too painful for CI, we can disable for now (in prod experiments, they run fine right ?). we might shift to google cloud build in some time for cls too, which is what we build in prod [beefy n1-standard-32 config]. just this local part is bothering me why.

**Comment by vanhauser-thc** [comment]
how easy is it for you to reproduce? maybe try the aflplusplus_asan variant?

**Comment by inferno-chromium** [comment]
fixed in https://github.com/google/fuzzbench/pull/1083
