### ISSUE TITLE
ERROR:root:Error generating HTML report. in local experiments

### ISSUE THREAD

**Issue by andreafioraldi** [google/fuzzbench#1357]
```
ERROR:root:Error generating HTML report. Extras: {'traceback': 'Traceback (most recent call last):\n  File "/work/src/experiment/reporter.py", line 73, in output_report\n    generate_report.generate_report(\n  File "/work/src/analysis/generate_report.py", line 235, in generate_report\n    experiment_ctx = experiment_results.ExperimentResults(\n  File "/work/src/analysis/experiment_results.py", line 97, in __init__\n    self.experiment_filestore = strip_gs_protocol(\n  File "/work/src/analysis/experiment_results.py", line 31, in strip_gs_protocol\n    raise ValueError(f\'{url} doesn\\\'t start with {protocol}\')\nValueError: /home/andrea/experiments/grammars-experiment-data doesn\'t start with gs://\n'}
```
It expects an URL but in local the experiment filestore is a path, `experiment_filestore: /home/andrea/experiments/grammars-experiment-data` in my yaml

How can I manually generate an HTML report after that an experiment finished?

**Comment by andreafioraldi** [comment]
@jonathanmetzman it seems that the cause is your last commit https://github.com/google/fuzzbench/commit/131ea6ede12f845f72de5aecef5f7a85efe777ff

**Comment by jonathanmetzman** [comment]
Thanks for reporting this.
I'll fix it later today

**Comment by andreafioraldi** [comment]
great, there is a way to generate the report after the experiment finished?
now i have the experiment but an empty reports folder

Il lun 21 mar 2022, 17:41 jonathanmetzman ***@***.***> ha
scritto:

**Comment by jonathanmetzman** [comment]
Umm...if this were a regular experiment, then yeah you could do so by running analysis/generate_report.py but I've never used it outside of a cloud expreriment. Maybe by setting [SQL_DATABASE_URL](https://github.com/google/fuzzbench/blob/master/database/utils.py#L32) to point to the sqlite db for your local experiment.
If you can't figure it out, send me the db and I'll get it working.

**Comment by andreafioraldi** [comment]
> Umm...if this were a regular experiment, then yeah you could do so by running analysis/generate_report.py but I've never used it outside of a cloud expreriment. Maybe by setting [SQL_DATABASE_URL](https://github.com/google/fuzzbench/blob/master/database/utils.py#L32) to point to the sqlite db for your local experiment. If you can't figure it out, send me the db and I'll get it working.

it worked
