### ISSUE TITLE
Unable to build curl_curl_fuzzer_http due to the version update of zlib

### ISSUE THREAD

**Issue by hugeh0ge** [google/fuzzbench#1369]
Hello, all.

I got the following error when I tried to start a local experiment with `curl_curl_fuzzer_http`: 

```
#20 [stage-1 13/13] RUN echo "Run fuzzer_build to build the target" && if [ ...
#20       digest: sha256:e7da7992fdfa392e1edfee44041281766e830c2fb6b2ce87d71359b1235b5351
#20         name: "[stage-1 13/13] RUN echo \"Run fuzzer_build to build the target\" && if [ -z \"$debug_builder\" ] ; then fuzzer_build; fi"
#20      started: 2022-03-29 07:57:40.616074631 +0000 UTC
#20 0.815 Run fuzzer_build to build the target
#20 0.890 FUZZ_TARGET = curl_fuzzer_http
#20 0.890 CFLAGS = -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -pthread -Wl,--no-as-needed -Wl,-ldl -Wl,-lm -Wno-unused-command-line-argument -O3
#20 0.890 CXXFLAGS = -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -pthread -Wl,--no-as-needed -Wl,-ldl -Wl,-lm -Wno-unused-command-line-argument -stdlib=libc++ -O3
#20 0.899 Building benchmark curl_curl_fuzzer_http with fuzzer coverage
#20 0.902 + ./ossfuzz.sh
#20 0.903 CC: clang
#20 0.903 CXX: clang++
#20 0.903 LIB_FUZZING_ENGINE: /usr/lib/libFuzzer.a
#20 0.903 CFLAGS: -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -pthread -Wl,--no-as-needed -Wl,-ldl -Wl,-lm -Wno-unused-command-line-argument -O3 -fprofile-instr-generate -fcoverage-mapping -gline-tables-only
#20 0.904 CXXFLAGS: -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -pthread -Wl,--no-as-needed -Wl,-ldl -Wl,-lm -Wno-unused-command-line-argument -stdlib=libc++ -O3 -fprofile-instr-generate -fcoverage-mapping -gline-tables-only
#20 0.904 ARCHITECTURE: x86_64
#20 0.904 FUZZ_TARGETS: curl_fuzzer_dict curl_fuzzer_file curl_fuzzer_ftp curl_fuzzer_gopher curl_fuzzer_http curl_fuzzer_https curl_fuzzer_imap curl_fuzzer_ldap curl_fuzzer_pop3 curl_fuzzer_rtmp curl_fuzzer_rtsp curl_fuzzer_scp curl_fuzzer_sftp curl_fuzzer_smb curl_fuzzer_smtp curl_fuzzer_tftp curl_fuzzer
#20 0.906 + [[ -d /src/curl_fuzzer ]]
#20 0.906 + SCRIPTDIR=/src/curl_fuzzer/scripts
#20 0.906 + DEPENDENCY=zlib
#20 0.906 + DEPENDENCYDIR=/src/zlib
#20 0.906 + INSTALLDIR=/src/curl_install
#20 0.906 + [[ -z /src/zlib ]]
#20 0.906 + [[ ! -d /src/zlib ]]
#20 0.907 + /src/curl_fuzzer/scripts/download_zlib.sh /src/zlib
#20 0.908 + wget https://www.zlib.net/zlib-1.2.11.tar.gz -O /tmp/zlib-1.2.11.tar.gz
#20 0.910 --2022-03-29 07:57:41--  https://www.zlib.net/zlib-1.2.11.tar.gz
#20 0.912 Resolving www.zlib.net (www.zlib.net)... 85.187.148.2
#20 1.225 Connecting to www.zlib.net (www.zlib.net)|85.187.148.2|:443... connected.
#20 1.629 HTTP request sent, awaiting response... 404 Not Found
#20 1.767 2022-03-29 07:57:42 ERROR 404: Not Found.
#20 1.767 
#20 1.789 Traceback (most recent call last):
#20 1.789   File "<string>", line 1, in <module>
#20 1.790   File "/src/fuzzers/coverage/fuzzer.py", line 33, in build
#20 1.790     utils.build_benchmark()
#20 1.790   File "/src/fuzzers/utils.py", line 82, in build_benchmark
#20 1.790     subprocess.check_call(['/bin/bash', '-ex', build_script], env=env)
#20 1.790   File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
#20 1.790     raise CalledProcessError(retcode, cmd)
#20 1.790 subprocess.CalledProcessError: Command '['/bin/bash', '-ex', '/src/build.sh']' returned non-zero exit status 1.
#20    completed: 2022-03-29 07:57:42.489817456 +0000 UTC
#20     duration: 1.873742825s
#20        error: "executor failed running [/bin/sh -c echo \"Run fuzzer_build to build the target\" && if [ -z \"$debug_builder\" ] ; then fuzzer_build; fi]: runc did not terminate sucessfully"

failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c echo "Run fuzzer_build to build the target" && if [ -z "$debug_builder" ] ; then fuzzer_build; fi]: runc did not terminate sucessfully
docker/generated.mk:558: recipe for target '.coverage-curl_curl_fuzzer_http-builder' failed
make: *** [.coverage-curl_curl_fuzzer_http-builder] Error 1
'}
ERROR:root:Failed to build measurer for curl_curl_fuzzer_http. Extras: {'traceback': 'Traceback (most recent call last):
  File "/work/src/experiment/build/builder.py", line 96, in build_measurer
    buildlib.build_coverage(benchmark)
  File "/work/src/experiment/build/local_build.py", line 58, in build_coverage
    result = make([image_name])
  File "/work/src/experiment/build/local_build.py", line 33, in make
    return new_process.execute(command, cwd=utils.ROOT_DIR)
  File "/work/src/common/new_process.py", line 124, in execute
    raise subprocess.CalledProcessError(retcode, command)
subprocess.CalledProcessError: Command '['make', '-j', 'build-coverage-curl_curl_fuzzer_http']' returned non-zero exit status 2.
'}
```

The message says `https://www.zlib.net/zlib-1.2.11.tar.gz` has become an invalid URL, and I actually confirmed this URL is invalid.
It seems like this is because zlib-1.2.12 is released a few days ago and `https://www.zlib.net/fossils/zlib-1.2.11.tar.gz` should be used instead.
So the fix itself would be easy.

The problem is that `download_zlib.sh` is under another repo (https://github.com/curl/curl-fuzzer/blob/master/scripts/download_zlib.sh) and the repo doesn't look so active. 
So, it may be reasonable to patch this from the fuzzbench side.
I'm still not sure if this issue should be resolved here, but anyways I post this.

**Comment by hugeh0ge** [comment]
I really appreciate your fast handling!
