### ISSUE TITLE
Local experiment: database is locked 

### ISSUE THREAD

**Issue by jiradeto** [google/fuzzbench#1371]
In local experiment, I got database locked error when running the scheduler. This somehow prevents scheduler to create new runner containers and consequently running the rest of the experiment becomes pointless as there is no trail runner to run fuzzer anymore. 

stack trace:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/work/src/experiment/scheduler.py", line 586, in schedule_loop
    while not all_trials_ended(experiment):
  File "/work/src/experiment/scheduler.py", line 105, in all_trials_ended
    return not get_experiment_trials(experiment).filter(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3346, in all
    return list(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3508, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3533, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT trial.id AS trial_id, trial.pair_idx AS trial_pair_idx, trial.fuzzer AS trial_fuzzer, trial.experiment AS trial_experiment, trial.benchmark AS trial_benchmark, t
rial.time_started AS trial_time_started, trial.time_ended AS trial_time_ended, trial.preemptible AS trial_preemptible, trial.preempted AS trial_preempted
FROM trial
WHERE trial.experiment = ? AND trial.time_ended IS NULL ORDER BY trial.id]
[parameters: ('init-exp',)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
INFO:root:Done measuring all trials.
INFO:root:Measuring all trials.
```

It'd be better if fuzzbench handles this database lock in a more graceful way so that the whole experiment won't get disrupted.

**Comment by jonathanmetzman** [comment]
Patch definitely welcome.
Do you know why it is locked?
I assume there was some other experiment running that died without removing some kind of lock right?
