### ISSUE TITLE
Error when generating coverage report

### ISSUE THREAD

**Issue by bhambleton** [google/fuzzbench#1383]
I am attempting to run a local experiment for part of a course project. Initial experiments to test my environment complete successfully, but no reports are generated.

The experiment is being run inside an Ubuntu 20.04.4 amd64 VM with Python 3.8.10 and docker 20.10.14. 

`make presubmit` reports (included only the skipped tests and warnings):
```
analysis/test_queries.py::test_get_experiment_data_fuzzer_stats SKIPPED  [ 14%]
experiment/test_runner.py::TestIntegrationRunner::test_integration_runner SKIPPED                                  [ 59%]
experiment/test_scheduler.py::test_create_trial_instance_local_experiment[benchmark1-gcr.io/fuzzbench/runners/fuzzer-a/benchmark1-fuzz-target] SKIPPED [ 61%]
experiment/test_scheduler.py::test_create_trial_instance_local_experiment[bloaty_fuzz_target-gcr.io/fuzzbench/runners/fuzzer-a/bloaty_fuzz_target-fuzz_target] SKIPPED [ 62%]
experiment/build/test_builder.py::test_build_all_measurers[True] SKIPPED                                           [ 66%]
experiment/build/test_builder.py::test_build_all_measurers[False] SKIPPED                                          [ 66%]
experiment/build/test_builder.py::TestIntegrationBuild::test_integration_build_all_fuzzer_benchmarks SKIPPED       [ 67%]
experiment/build/test_builder.py::TestIntegrationBuild::test_integration_build_oss_fuzz_projects SKIPPED           [ 67%]
experiment/build/test_builder.py::TestIntegrationBuild::test_integration_build_all_measurers SKIPPED               [ 67%]
experiment/build/test_builder.py::TestIntegrationBuild::test_integration_build_oss_fuzz_project_measurers SKIPPED  [ 68%]
experiment/build/test_builder.py::TestBuildChangedBenchmarksOrFuzzers::test_build_changed_fuzzers SKIPPED          [ 68%]
experiment/build/test_builder.py::TestBuildChangedBenchmarksOrFuzzers::test_build_changed_benchmarks SKIPPED       [ 68%]
experiment/build/test_builder.py::TestBuildChangedBenchmarksOrFuzzers::test_build_measurers_benchmarks SKIPPED     [ 69%]
experiment/measurer/test_measure_manager.py::test_measure_all_trials_no_more SKIPPED                               [ 75%]
experiment/measurer/test_measure_manager.py::TestIntegrationMeasurement::test_measure_snapshot_coverage SKIPPED    [ 77%]

experiment/measurer/test_run_coverage.py::TestIntegrationRunCoverage::test_integration_do_coverage_run_crash SKIPPED [ 79%]
experiment/measurer/test_run_coverage.py::TestIntegrationRunCoverage::test_integration_do_coverage_run_no_crash SKIPPED [ 79%]
experiment/measurer/test_run_coverage.py::TestIntegrationRunCoverage::test_integration_do_coverage_run_max_total_timeout SKIPPED [ 79%]
experiment/measurer/test_run_crashes.py::TestIntegrationRunCoverage::test_integration_do_coverage_run_crash SKIPPED [ 80%]
==================================================== warnings summary ====================================================
.venv/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:10
  /home/btham/Projects/fuzzbench/.venv/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:10: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    _nlv = LooseVersion(_np_version)

.venv/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:11
  /home/btham/Projects/fuzzbench/.venv/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:11: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    np_version_under1p17 = _nlv < LooseVersion("1.17")

.venv/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:12
  /home/btham/Projects/fuzzbench/.venv/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:12: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    np_version_under1p18 = _nlv < LooseVersion("1.18")

.venv/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:13
  /home/btham/Projects/fuzzbench/.venv/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:13: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    _np_version_under1p19 = _nlv < LooseVersion("1.19")

.venv/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:14
  /home/btham/Projects/fuzzbench/.venv/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py:14: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    _np_version_under1p20 = _nlv < LooseVersion("1.20")

.venv/lib/python3.8/site-packages/setuptools/_distutils/version.py:351
.venv/lib/python3.8/site-packages/setuptools/_distutils/version.py:351
.venv/lib/python3.8/site-packages/setuptools/_distutils/version.py:351
  /home/btham/Projects/fuzzbench/.venv/lib/python3.8/site-packages/setuptools/_distutils/version.py:351: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    other = LooseVersion(other)

.venv/lib/python3.8/site-packages/pandas/compat/numpy/function.py:120
.venv/lib/python3.8/site-packages/pandas/compat/numpy/function.py:120
  /home/btham/Projects/fuzzbench/.venv/lib/python3.8/site-packages/pandas/compat/numpy/function.py:120: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    if LooseVersion(__version__) >= LooseVersion("1.17.0"):

.venv/lib/python3.8/site-packages/pandas/compat/_optional.py:116
  /home/btham/Projects/fuzzbench/.venv/lib/python3.8/site-packages/pandas/compat/_optional.py:116: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    if distutils.version.LooseVersion(version) < minimum_version:

.venv/lib/python3.8/site-packages/seaborn/rcmod.py:82
  /home/btham/Projects/fuzzbench/.venv/lib/python3.8/site-packages/seaborn/rcmod.py:82: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    if LooseVersion(mpl.__version__) >= "3.0":

.venv/lib/python3.8/site-packages/clusterfuzz/stacktraces/constants.py:75
  /home/btham/Projects/fuzzbench/.venv/lib/python3.8/site-packages/clusterfuzz/stacktraces/constants.py:75: FutureWarning: Possible nested set at position 4
    CHROME_CHECK_FAILURE_REGEX = re.compile(

.venv/lib/python3.8/site-packages/clusterfuzz/stacktraces/constants.py:200
  /home/btham/Projects/fuzzbench/.venv/lib/python3.8/site-packages/clusterfuzz/stacktraces/constants.py:200: FutureWarning: Possible nested set at position 3
    SECURITY_CHECK_FAILURE_REGEX = re.compile(

.venv/lib/python3.8/site-packages/clusterfuzz/stacktraces/constants.py:202
  /home/btham/Projects/fuzzbench/.venv/lib/python3.8/site-packages/clusterfuzz/stacktraces/constants.py:202: FutureWarning: Possible nested set at position 3
    SECURITY_DCHECK_FAILURE_REGEX = re.compile(

analysis/test_data_utils.py::test_experiment_rank_by_average_normalized_score
  /home/btham/Projects/fuzzbench/analysis/test_data_utils.py:355: FutureWarning: The 'check_less_precise' keyword in testing.assert_*_equal is deprecated and will be removed in a future version. You can stop passing 'check_less_precise' to silence this warning.
    pd_test.assert_series_equal(ranking,

-- Docs: https://docs.pytest.org/en/stable/warnings.html

===================================== 289 passed, 24 skipped, 16 warnings in 35.14s ======================================
Success.

```

This is my config file which only runs 1 trial and short trial time to see if it works:

```yaml
# The number of trials of a fuzzer-benchmark pair.
trials: 1

# The amount of time in seconds that each trial is run for.
# 1 day = 24 * 60 * 60 = 86400
max_total_time: 60

# The location of the docker registry.
# FIXME: Support custom docker registry.
# See https://github.com/google/fuzzbench/issues/777
docker_registry: gcr.io/fuzzbench

# The local experiment folder that will store most of the experiment data.
# Please use an absolute path.
experiment_filestore: /tmp/experiment-data

# The local report folder where HTML reports and summary data will be stored.
# Please use an absolute path.
report_filestore: /tmp/report-data

# Flag that indicates this is a local experiment.
local_experiment: true
```

I am starting the experiment with the command:
```console
PYTHONPATH=. python3 experiment/run_experiment.py \
    --experiment-config experiment-config.yaml \
    --benchmarks openssl_x509 \
    --experiment-name openssl-aflfast \
    --fuzzers aflfast \
    --concurrent-builds 1 \
    --runners-cpus 1 \
    --measurers-cpus 1
```

Towards the end of execution the following error is generated:

```console
INFO:root:Reading experiment data from db.
INFO:root:Done reading experiment data from db.
WARNING:root:No snapshot data.
INFO:root:Measuring all trials.
INFO:root:Done measuring all trials.
INFO:root:Finished measure loop.
INFO:root:Start generating coverage reports.
INFO:root:Generating coverage report for benchmark: openssl_x509 fuzzer: aflfast.
INFO:root:Merging profdata for fuzzer: aflfast,benchmark: openssl_x509.
ERROR:root:Profdata files merging failed.
ERROR:root:Error occurred when generating coverage report. 
Extras: {
	'traceback': 'Traceback (most recent call last):
		File "/work/src/experiment/measurer/coverage_utils.py", line 73, in generate_coverage_report
 			coverage_reporter.generate_coverage_summary_json()
		File "/work/src/experiment/measurer/coverage_utils.py", line 140, in generate_coverage_summary_json
			result = generate_json_summary(coverage_binary,
		File "/work/src/experiment/measurer/coverage_utils.py", line 267, in generate_json_summary
			with open(output_file, \'w\') as dst_file:
	FileNotFoundError: [Errno 2] No such file or directory: \'/work/measurement-folders/openssl_x509-aflfast/merged.json\'\n'
}

INFO:root:Finished generating coverage reports.
INFO:root:Finished measuring.
INFO:root:Reading experiment data from db.
INFO:root:Done reading experiment data from db.
WARNING:root:No snapshot data.
INFO:root:Finished scheduling.
INFO:root:Reading experiment data from db.
INFO:root:Done reading experiment data from db.
WARNING:root:No snapshot data.
INFO:root:Experiment ended.
```

I have reran with different fuzzer and benchmark combinations, all giving the same error and `/tmp/report-data/` is always empty. There is, however, experiment data in the `/tmp/experiment-data/` directory.

Thanks for your help.

**Comment by jonathanmetzman** [comment]
OK so there's definitely a way to generate a report with the data from your experiment. Let me figure this out and get back to you.

**Comment by bhambleton** [comment]
Is it possible that having only 1 trial and such a short total time for each trial in the configuration does not generate enough data ? 

I adjusted `trials` to 2 and `max_total_time` to 3600 and the reports were auto generated without error. So I may have opened this issue prematurely.

**Comment by bhambleton** [comment]
Closing the issue because adjusting number of trials and trial time fixed my original issue

**Comment by jonathanmetzman** [comment]
I think using only one fuzzer in an experiment breaks things
