### ISSUE TITLE
Local experiment: `http://metadata.google.internal` is not accessed.

### ISSUE THREAD

**Issue by Ricardio609** [google/fuzzbench#1401]
```
$ PYTHONPATH=. python3 experiment/run_experiment.py --experiment-config experiment-config.yaml --benchmarks freetype2-2017  --experiment-name "first" --fuzzers afl
Traceback (most recent call last):
  File "experiment/run_experiment.py", line 654, in <module>
    sys.exit(main())
  File "experiment/run_experiment.py", line 521, in main
    logs.initialize()
  File "/home/enso/Desktop/fuzzbench/common/logs.py", line 64, in initialize
    if utils.is_local():
  File "/home/enso/Desktop/fuzzbench/common/utils.py", line 49, in is_local
    urllib.request.urlopen('http://metadata.google.internal')
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1383, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.8/urllib/request.py", line 1358, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 285, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```

**Comment by jonathanmetzman** [comment]
Are your running this on google cloud?

**Comment by Ricardio609** [comment]
> 

sorry, I only run these in my local enviroment. This http connection seems not to respones.
