### ISSUE TITLE
Fuzzbench failed to launch trials in local experiment

### ISSUE THREAD

**Issue by apach301** [google/fuzzbench#1406]
Hi! I'm using fuzzbench for local experiments, and since the last week it starts failing to launch trials. The experiment itself continues to work and measurers working but there are no any docker with running trials, only gcr.io/fuzzbench/dispatcher-image is active. When I attached to the docker and tried to launch trial script manually (/bin/bash /tmp/r-symqemu-test-13-1442-start-docker.sh) it fails with this message:
```
Traceback (most recent call last):
  File "/src/experiment/runner.py", line 35, in <module>
    from common import filestore_utils
  File "/src/common/filestore_utils.py", line 17, in <module>
    from common import gsutil
  File "/src/common/gsutil.py", line 16, in <module>
    from common import new_process
  File "/src/common/new_process.py", line 22, in <module>
    from common import logs
  File "/src/common/logs.py", line 21, in <module>
    import google.cloud.logging
  File "/usr/local/lib/python3.8/site-packages/google/cloud/logging/__init__.py", line 22, in <module>
    from google.cloud.logging.client import Client
  File "/usr/local/lib/python3.8/site-packages/google/cloud/logging/client.py", line 21, in <module>
    from google.cloud.logging import _gapic
  File "/usr/local/lib/python3.8/site-packages/google/cloud/logging/_gapic.py", line 20, in <module>
    from google.cloud.logging_v2.gapic.config_service_v2_client import ConfigServiceV2Client
  File "/usr/local/lib/python3.8/site-packages/google/cloud/logging_v2/__init__.py", line 17, in <module>
    from google.cloud.logging_v2 import types
  File "/usr/local/lib/python3.8/site-packages/google/cloud/logging_v2/types.py", line 34, in <module>
    from google.cloud.logging_v2.proto import log_entry_pb2
  File "/usr/local/lib/python3.8/site-packages/google/cloud/logging_v2/proto/log_entry_pb2.py", line 66, in <module>
    _descriptor.FieldDescriptor(
  File "/usr/local/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Comment by apach301** [comment]
Found out that specifying environment variable PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python at docker startup script fixes this issue. I don't know how much this solution is reliable, but here is fast fix: #1407
