### ISSUE TITLE
Private experiments broken

### ISSUE THREAD

**Issue by jonathanmetzman** [google/fuzzbench#1658]
error is
```
Traceback (most recent call last):
  File "/work/src/experiment/cloud/service_account_key.py", line 24, in <module>
    from common import gcloud
  File "/work/src/common/gcloud.py", line 21, in <module>
    from common import experiment_utils
  File "/work/src/common/experiment_utils.py", line 19, in <module>
    from common import benchmark_utils
  File "/work/src/common/benchmark_utils.py", line 22, in <module>
    from common import logs
  File "/work/src/common/logs.py", line 22, in <module>
    from google.cloud.logging_v2.handlers.handlers import CloudLoggingHandler
ModuleNotFoundError: No module named 'google.cloud.logging_v2.handlers'
```

I don't know what's causing this, but I know nothing is building the dispatcher image in the private docker registry. maybe it is obsolete and in need of an update.

**Comment by jonathanmetzman** [comment]
I fixed this
