### ISSUE TITLE
local experiment issue : Local uncommitted changes found, exiting - raise ValidationError('Local uncommitted changes found, exiting.')

### ISSUE THREAD

**Issue by Microsvuln** [google/fuzzbench#1983]
Hi .

For running a local test experiment I have the following error :

```
PYTHONPATH=. python3 experiment/run_experiment.py --experiment-config experiment-config.yaml --benchmarks curl_curl_fuzzer_http --experiment-name $EXPERIMENT_NAME --fuzzers afl libfuzzer
Traceback (most recent call last):
  File "/home/user/fuzz/eval/fuzzbench/experiment/run_experiment.py", line 773, in <module>
    sys.exit(main())
  File "/home/user/fuzz/eval/fuzzbench/experiment/run_experiment.py", line 615, in main
    return run_experiment_main()
  File "/home/user/fuzz/eval/fuzzbench/experiment/run_experiment.py", line 755, in run_experiment_main
    start_experiment(args.experiment_name,
  File "/home/user/fuzz/eval/fuzzbench/experiment/run_experiment.py", line 318, in start_experiment
    check_no_uncommitted_changes()
  File "/home/user/fuzz/eval/fuzzbench/experiment/run_experiment.py", line 286, in check_no_uncommitted_changes
    raise ValidationError('Local uncommitted changes found, exiting.')
__main__.ValidationError: Local uncommitted changes found, exiting.
```

Anyone faced the same issue? Any workarounds ?

Thanks.

**Comment by Microsvuln** [comment]
This solved the problem :

` git commit -am foo `

Thanks @vanhauser-thc !
