### ISSUE TITLE
Questions about honggfuzz coverage collection

### ISSUE THREAD

**Issue by yifengchen-cc** [google/fuzzbench#326]
It seems that all types of fuzzers(afl,libfuzzer,honggfuzz) are collected through [do_coverage_run ()](https://github.com/google/fuzzbench/blob/master/experiment/run_coverage.py#L43).Command is as follows:

```shell
fuzz-target -merge=1 -dump_coverage=1 -artifact_prefix= crashes -timeout=5 -rss_limit_mb=2048 -max_total_time=60 /tmp/tmp_fb4x7p5   corpus/ 
```

But when I enter a running container(gcr.io/fuzzbench/runners/honggfuzz/libpng-1.2.56) and run the following command, it returns following error:

```shell
root@89b26af17169:/out# mkdir crashes
root@89b26af17169:/out# mkdir merges
root@89b26af17169:/out# ./fuzz-target -merge=1 -dump_coverage=1 -artifact_prefix=crashes/ -timeout=5 -rss_limit_mb=2048 -max_total_time=60 merges/  corpus/
Accepting input from 'corpus/'
Usage for fuzzing: honggfuzz -P [flags] -- ./fuzz-target
[2020-05-12T02:03:05+0000][E][47] HonggfuzzRunFromFile():99 Couldn't read data from stdin: Is a directory
```

I copied the fuzz_target and tested it with test_integration_do_coverage_run_no_crash () which also failed:

```shell
(.venv) root:/fuzzbench#cat 1.py
from experiment import test_run_coverage
if __name__ == '__main__':
    test = test_run_coverage.TestIntegrationRunCoverage()  
 test.test_integration_do_coverage_run_no_crash('/fuzzbench/experiment/test_data/test_run_coverage')
(.venv) root:/fuzzbench# python 1.py
['/fuzzbench/experiment/test_data/test_run_coverage/fuzz-target', '-merge=1', '-dump_coverage=1', '-artifact_prefix=/fuzzbench/experiment/test_data/test_run_coverage/crashes/', '-timeout=5', '-rss_limit_mb=2048', '-max_total_time=60', '/tmp/tmp_fb4x7p5', '/fuzzbench/experiment/test_data/test_run_coverage/corpus']
ERROR:root:Coverage run failed.
Traceback (most recent call last):
  File "1.py", line 24, in <module>
    test.test_integration_do_coverage_run_no_crash('/fuzzbench/experiment/test_data/test_run_coverage')
  File "/fuzzbench_proj/fuzzbench/experiment/test_run_coverage.py", line 86, in test_integration_do_coverage_run_no_crash
    _assert_sancov_files(sancov_dir)
  File "/fuzzbench_proj/fuzzbench/experiment/test_run_coverage.py", line 53, in _assert_sancov_files
    assert glob.glob(pattern)
AssertionError
```

Is there something wrong with the command I entered?

**Comment by inferno-chromium** [comment]
Coverage is collected independent of the fuzzer, using libFuzzer+sancov
See https://github.com/google/fuzzbench/blob/master/fuzzers/coverage/builder.Dockerfile#L23
Coverage binaries can be seen in experiment data e.g.
http://commondatastorage.googleapis.com/fuzzbench-data/index.html?prefix=2020-05-11/coverage-binaries/
