### ISSUE TITLE
make presubmit stalls when using python3.8. 

### ISSUE THREAD

**Issue by Tanq16** [google/fuzzbench#411]
Hi! On using python3.8, `make presubmit` stalls at `test_build_all_measures` from test_builder.py. 
Trace after interrupt is as follows -
```
experiment/test_scheduler.py::test_get_preempted_trials_new_preempted PASSED                                          [ 77%]
experiment/build/test_builder.py::test_build_all_measurers[True] ^CTraceback (most recent call last):
  File "presubmit.py", line 377, in <module>
    sys.exit(main())
  File "presubmit.py", line 356, in main
    success = do_checks(relevant_files)
  File "presubmit.py", line 301, in do_checks
    if not do_tests():
  File "presubmit.py", line 281, in do_tests
    returncode = subprocess.run(BASE_PYTEST_COMMAND, check=False).returncode
  File "/usr/lib/python3.8/subprocess.py", line 491, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1016, in communicate
    self.wait()
  File "/usr/lib/python3.8/subprocess.py", line 1079, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1804, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.8/subprocess.py", line 1762, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
make: *** [Makefile:31: presubmit] Interrupt
```

Also, continuing to a test-run after the interrupt raises the following exception from `/google/auth/default.py` -
```
raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
```

Python3.7 works well.

Thanks
Tanishq

**Comment by Tanq16** [comment]
Gist to a run of pytest -
https://gist.github.com/Tanq16/a9b25ab81f24ce88346154299370c62b

**Comment by jonathanmetzman** [comment]
Probably a pool issue. 
Also worth noting that a lot of the pip installs fail with python3.8 which seems pretty bad.

**Comment by jonathanmetzman** [comment]
I fixed this so that this test is disabled on python3.8
