### ISSUE TITLE
aflcc is disabled due to failure to compile on 3 benchmarks (systemd, php, perl)

### ISSUE THREAD

**Issue by inferno-chromium** [google/fuzzbench#586]
E.g. try
make build-aflcc-perl-5.21.7

```
Run: /path/to/afl/aflc-clang-fast /out/fuzz-target.bc -o /out/fuzz-target <additional LDFLAGS>
[post_build] Generating original afl build
[+] Edge Map size used: 64 KB
/tmp/fuzz-target-2c007f.o: In function `LLVMFuzzerTestOneInput':
/out/fuzz-target.bc:(.text+0x343): undefined reference to `PL_use_safe_putenv'
/out/fuzz-target.bc:(.text+0x356): undefined reference to `Perl_sys_init3'
/out/fuzz-target.bc:(.text+0x35c): undefined reference to `PL_do_undump'
/out/fuzz-target.bc:(.text+0x380): undefined reference to `perl_alloc'
/out/fuzz-target.bc:(.text+0x3b5): undefined reference to `perl_construct'
/out/fuzz-target.bc:(.text+0x3bb): undefined reference to `PL_perl_destruct_level'
/out/fuzz-target.bc:(.text+0x3de): undefined reference to `PL_exit_flags'
/out/fuzz-target.bc:(.text+0x3fa): undefined reference to `perl_parse'
/out/fuzz-target.bc:(.text+0x426): undefined reference to `perl_run'
/out/fuzz-target.bc:(.text+0x449): undefined reference to `PL_sig_name'
/out/fuzz-target.bc:(.text+0x49f): undefined reference to `PL_sig_num'
/out/fuzz-target.bc:(.text+0x4a7): undefined reference to `Perl_rsignal_state'
/out/fuzz-target.bc:(.text+0x4ae): undefined reference to `PL_csighandlerp'
/out/fuzz-target.bc:(.text+0x4d6): undefined reference to `Perl_rsignal'
/out/fuzz-target.bc:(.text+0x4fa): undefined reference to `PL_sig_name'
/out/fuzz-target.bc:(.text+0x549): undefined reference to `perl_destruct'
/out/fuzz-target.bc:(.text+0x555): undefined reference to `perl_free'
/out/fuzz-target.bc:(.text+0x55a): undefined reference to `Perl_sys_term'
/tmp/fuzz-target-2c007f.o: In function `xs_init()':
/out/fuzz-target.bc:(.text+0x68d): undefined reference to `boot_DynaLoader'
/out/fuzz-target.bc:(.text+0x698): undefined reference to `Perl_newXS'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/src/fuzzer.py", line 303, in build
    post_build(fuzz_target)
  File "/src/fuzzer.py", line 259, in post_build
    raise ValueError('command "{command}" failed'.format(command=bin1_cmd))
ValueError: command "/afl/aflc-clang-fast++ -I/usr/local/include/c++/v1/ -stdlib=libc++ -std=c++11 -O3 /out/fuzz-target.bc -o /out/fuzz-target-original -lpthread -lm  -lz -larchive -lglib-2.0 -ldl -lbsd" failed
The command '/bin/sh -c python3 -u -c "from fuzzers import utils; utils.initialize_flags(); import fuzzer; fuzzer.build()"' returned a non-zero code: 1
```

**Comment by inferno-chromium** [comment]
@laurentsimon - can you please check if this is easy to fix, otherwise, lets remove aflcc for now.

**Comment by inferno-chromium** [comment]
Here is the complete list:

('aflcc', 'systemd_fuzz-link-parser')
('aflcc', 'php_php-fuzz-parser')
('aflcc', 'perl-5.21.7')

More output:
```
Run: /path/to/afl/aflc-clang-fast /out/php-fuzz-parser.bc -o /out/php-fuzz-parser <additional LDFLAGS>
[post_build] Generating original afl build
[+] Edge Map size used: 64 KB
/tmp/php-fuzz-parser-af9329.o: In function `zif_proc_open':
/out/php-fuzz-parser.bc:(.text+0x4eee4b): undefined reference to `openpty'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/src/fuzzer.py", line 303, in build
    post_build(fuzz_target)
  File "/src/fuzzer.py", line 259, in post_build
    raise ValueError('command "{command}" failed'.format(command=bin1_cmd))
ValueError: command "/afl/aflc-clang-fast++ -I/usr/local/include/c++/v1/ -stdlib=libc++ -std=c++11 -O3 /out/php-fuzz-parser.bc -o /out/php-fuzz-parser-original -lpthread -lm  -lz -larchive -lglib-2.0 -ldl -lbsd -lresolv" failed
```

**Comment by vanhauser-thc** [comment]
I already opened an issue at aflcc a few days ago: https://github.com/Samsung/afl_cc/issues/1

**Comment by laurentsimon** [comment]
Thanks for reporting this. Unfortunately I did not integrate aflcc for
these 3 fuzzers, since we were not using them until now.
Can you confirm this is a new addition to our benchmark targets?

It will take some effort for me to port, because I need to extract a .bc
file for each target and most OSS-fuzz projects are not standalone. Let's
remove aflcc for now.

I'll keep a note that I need to fix it.

Thanks!

**Comment by inferno-chromium** [comment]
@laurentsimon - ping, it will be nice to evaluate aflcc with our current set of fuzzers. How much work is left here.

**Comment by laurentsimon** [comment]
it takes quite some effort for each integration. It's basically the same
effort as for KLEE.
I also want to double-check the current integration. In the previous runs
we made, aflcc would sometimes be worse than afl. That should not happen.
The other question is whether we should prioritize aflcc over KLEE...

**Comment by inferno-chromium** [comment]
> it takes quite some effort for each integration. It's basically the same effort as for KLEE. I also want to double-check the current integration. In the previous runs we made, aflcc would sometimes be worse than afl. That should not happen. The other question is whether we should prioritize aflcc over KLEE...

Nah, you are right KLEE should be definitely a priority. I will try to run a aflcc experiment without these benchmarks. Want to ensure that 08-23 experiment finishes first, so this can just merge with it.
