### ISSUE TITLE
Local: SQLite database is locked when generating report

### ISSUE THREAD

**Issue by jiradeto** [google/fuzzbench#623]
Git hash: a634c2f5d1c78af6ee1b0f6165bff951a600078d

When running local experiment with several trails I got the following error:

```
ERROR:root:Error generating HTML report. Extras: {'traceback': 'Traceback (most recent call last):
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/work/src/experiment/scheduler.py", line 597, in schedule_loop
    while not all_trials_ended(experiment):
  File "/work/src/experiment/scheduler.py", line 104, in all_trials_ended
    models.Trial.time_ended.is_(None)).all()
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3233, in all
    return list(self)
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3389, in __iter__
    return self._execute_and_instances(context)
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3414, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT trial.id AS trial_id, trial.fuzzer AS trial_fuzzer, trial.experiment AS trial_experiment, trial.benchmark AS trial_benchmark, trial.time_started AS trial_time_started, trial.time_ended AS tr$
al_time_ended, trial.preemptible AS trial_preemptible, trial.preempted AS trial_preempted
FROM trial
WHERE trial.experiment = ? AND trial.time_ended IS NULL ORDER BY trial.id]
[parameters: ('aug3',)]
(Background on this error at: http://sqlalche.me/e/e3q8)
```

experiment-config.yaml:
```yaml
experiment: test-experiment
trials: 7
max_total_time: 86400
docker_registry: gcr.io/fuzzbench
experiment_filestore: /expr/out/experiment-data
report_filestore: /expr/out/web-reports
local_experiment: true
benchmarks: "benchmark-1,benchmark-2"
git_hash: "git-hash"
```

and the command I used to run an experiment:
```
PYTHONPATH=. python3 experiment/run_experiment.py \
--experiment-config /expr/local-experiment-config.yaml \
--benchmarks freetype2-2017 lcms-2017-03-21 proj4-2017-08-14 sqlite3_ossfuzz libxml2-v2.9.2 bloaty_fuzz_target \
--experiment-name aug3 \
--fuzzers afl aflfast fairfuzz aflsmart aflplusplus afl_qemu
```

I am not sure if there is a limitation for the number of trails, fuzzers, or benchmakes that I am able to run locally?

**Comment by jonathanmetzman** [comment]
I can try this but are you sure you are only running one experiment at a time? Maybe delete the db file It should be in `/expr/out/experiment-data/local.db`
I'm surprised this is happening because we should only have at most 2 thread/process writing to the db at any given time.

**Comment by jonathanmetzman** [comment]
The best fix I can think of for this is to get postgres working locally.

**Comment by jiradeto** [comment]
> I can try this but are you sure you are only running one experiment at a time? Maybe delete the db file It should be in `/expr/out/experiment-data/local.db`
> I'm surprised this is happening because we should only have at most 2 thread/process writing to the db at any given time.

Yes, I think I started with a clean state. I ran one experiment at the time, and also I remove the whole directory `/expr/out/` before I start a new experiment.

Is there an option that I can switch to Postgres for local experiment @jonathanmetzman?

**Comment by jonathanmetzman** [comment]
Not implemented now. It might be easy though. I'd change https://github.com/google/fuzzbench/blob/master/experiment/run_experiment.py#L296 to not set SQL_DATABASE_URL and set POSTGRES_PASSWORD.
Then [this codepath ](https://github.com/google/fuzzbench/blob/master/database/utils.py#L37) will be taken during an experiment to use the postgres db on the default port at 127.0.0.1

**Comment by jiradeto** [comment]
fixed by https://github.com/google/fuzzbench/pull/1429
