### ISSUE TITLE
Lot of retry time wasted in (aflplusplus_optimal,openssl_x509)

### ISSUE THREAD

**Issue by inferno-chromium** [google/fuzzbench#675]
Looks like crazy 2-3 hours wasted in these retries and looks like it fails everytime. @vanhauser-thc, can this combination be fixed or any workaround. Otherwise, i can think later if we need to maintain a blacklist to avoid wasting time on repeats.

**Comment by inferno-chromium** [comment]
Looks like 2 hr hang on this execution.

```
${LDCMD:-/afl/afl-clang-lto} -pthread -m64 -fno-omit-frame-pointer -g -Wa,--noexecstack -Qunused-arguments -pthread -Wl,--no-as-needed -Wl,-ldl -Wl,-lm -Wno-unused-command-line-argument -O3 -pthread -Wno-unused-command-line-argument -O3 -fno-sanitize=alignment -L.  -Wl,--no-as-needed -Wl,-ldl -Wl,-lm \
	-o fuzz/bignum-test \
	fuzz/bignum-test-bin-bignum.o \
	fuzz/bignum-test-bin-test-corpus.o \
	-lcrypto -ldl -pthread 
clang: error: unable to execute command: Killed
clang: error: linker command failed due to signal (use -v to see invocation)
make[1]: *** [apps/openssl] Error 254
make[1]: *** Waiting for unfinished jobs....
Makefile:12889: recipe for target 'apps/openssl' failed
make[1]: Leaving directory '/src/openssl'
Makefile:2230: recipe for target 'build_sw' failed
make: *** [build_sw] Error 2
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/src/fuzzer.py", line 52, in build
    aflplusplus_fuzzer.build("lto", "dynamic", "laf")
  File "/src/fuzzers/aflplusplus/fuzzer.py", line 124, in build
    utils.build_benchmark()
  File "/src/fuzzers/utils.py", line 50, in build_benchmark
    subprocess.check_call(['/bin/bash', '-ex', build_script], env=env)
  File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-ex', '/src/build.sh']' returned non-zero exit status 2.
The command '/bin/sh -c PYTHONPATH=$SRC python3 -u -c "from fuzzers import utils; utils.initialize_flags(); import fuzzer; fuzzer.build()"' returned a non-zero code: 1
````

**Comment by vanhauser-thc** [comment]
that is weird as it build previously (with the same commit id) without problems.
I can switch it to pcguard instead. a major lto change is coming anyway, for which  #646 would be very good to have.

I will have to push a PR for the change from a different repo/account, gimme some minutes
