### ISSUE TITLE
Local: cov_summary.json file not found

### ISSUE THREAD

**Issue by jiradeto** [google/fuzzbench#708]
I was running local experiment and got the following error. (Fuzzbench commit `3720603`)

```
INFO:root:Done measuring all trials.
INFO:root:Finished measure loop.
INFO:root:Storing all fuzzer-benchmark pairs for final coverage data.
INFO:root:Measuring covered region: trial_id = 9.
INFO:root:Measuring covered region: trial_id = 10.
INFO:root:Measuring covered region: trial_id = 1.
INFO:root:Measuring covered region: trial_id = 2.
INFO:root:Measuring covered region: trial_id = 3.
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/work/src/experiment/measurer.py", line 73, in measure_main
    coverage_utils.store_coverage_data(experiment_config)
  File "/work/src/experiment/coverage_utils.py", line 208, in store_coverage_data
    store_covered_region(experiment, fuzzer, benchmark)
  File "/work/src/experiment/coverage_utils.py", line 219, in store_covered_region
    covered_regions = get_covered_region(experiment, fuzzer, benchmark)
  File "/work/src/experiment/coverage_utils.py", line 243, in get_covered_region
    trial_coverage.generate_summary(0, summary_only=False)
  File "/work/src/experiment/coverage_utils.py", line 311, in generate_summary
    with open(self.cov_summary_file, 'w') as output_file:
FileNotFoundError: [Errno 2] No such file or directory: '/work/measurement-folders/freetype2-2017-afl/trial-3/reports/cov_summary.json'
INFO:root:Dispatcher finished.
```

**Comment by inferno-chromium** [comment]
Please provide the set of commands you were running.

**Comment by jiradeto** [comment]
The command I used to start the experiment:
```
PYTHONPATH=. python3 experiment/run_experiment.py \
--experiment-config /pfm/local-experiment-config.yaml \
--benchmarks freetype2-2017 lcms-2017-03-21 libpng-1.2.56 sqlite3_ossfuzz libxml2-v2.9.2 bloaty_fuzz_target \ 
--experiment-name sep-1 \
--fuzzers afl fairfuzz aflplusplus
```

and my experiment configuration is:

```
experiment: test-experiment
trials: 20
max_total_time: 86400
docker_registry: gcr.io/fuzzbench
experiment_filestore: /fuzzbench-expr/out/experiment-data
report_filestore: /fuzzbench-expr/out/web-reports
local_experiment: true
benchmarks: "benchmark-1,benchmark-2"
git_hash: "git-hash"
```

**Comment by inferno-chromium** [comment]
If you sync to master, and uptake https://github.com/google/fuzzbench/pull/714, then it should fix it. You can try first with a lower max_total_time like 900, and lower trials like 2 to check if things work. Then can run the full experiment.

**Comment by inferno-chromium** [comment]
Actually ignore my last comment, didnt realize you were using local_experiment. local_experiment is still experimental.

**Comment by inferno-chromium** [comment]
Actually now it all works, only at the end there is some weird sql exception. If you exit from it, you are in docker shell, with reports in your | report_filestore| location. Please note that we are still fixing bugs in this and hence haven't documented it.

```
INFO:root:Start generating coverage reports.
INFO:root:Generating coverage report for benchmark: freetype2-2017 fuzzer: libfuzzer.
INFO:root:Merging profdata for fuzzer: libfuzzer,benchmark: freetype2-2017.
INFO:root:Finished generating coverage report.
INFO:root:Generating coverage report for benchmark: freetype2-2017 fuzzer: afl.
INFO:root:Merging profdata for fuzzer: afl,benchmark: freetype2-2017.
INFO:root:Finished generating coverage report.
INFO:root:Finished generating coverage reports.
INFO:root:Finished measuring.
INFO:root:Finished scheduling.
ERROR:root:Error conducting experiment. Extras: {'traceback': 'Traceback (most recent call last):\n  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1173, in _execute_context\n    context = constructor(dialect, self, conn, *args)\n  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 775, in _init_compiled\n    self.cursor = self.create_cursor()\n  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 1131, in create_cursor\n    return self._dbapi_connection.cursor()\n  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 978, in cursor\n    return self.connection.cursor(*args, **kwargs)\nsqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139631497549568 and this is thread id 139633173968640.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/work/src/experiment/dispatcher.py", line 191, in main\n    dispatcher_main()\n  File "/work/src/experiment/dispatcher.py", line 177, in dispatcher_main\n    _record_experiment_time_ended(experiment.experiment_name)\n  File "/work/src/experiment/dispatcher.py", line 76, in _record_experiment_time_ended\n    models.Experiment.name == experiment_name).one()\n  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3347, in one\n    ret = self.one_or_none()\n  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3316, in one_or_none\n    ret = list(self)\n  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3389, in __iter__\n    return self._execute_and_instances(context)\n  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3414, in _execute_and_instances\n    result = conn.execute(querycontext.statement, self._params)\n  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 982, in execute\n    return meth(self, multiparams, params)\n  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection\n    return connection._execute_clauseelement(self, multiparams, params)\n  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement\n    distilled_params,\n  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1176, in _execute_context\n    e, util.text_type(statement), parameters, None, None\n  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception\n    util.raise_from_cause(sqlalchemy_exception, exc_info)\n  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause\n    reraise(type(exception), exception, tb=exc_tb, cause=cause)\n  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise\n    raise value.with_traceback(tb)\n  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1173, in _execute_context\n    context = constructor(dialect, self, conn, *args)\n  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 775, in _init_compiled\n    self.cursor = self.create_cursor()\n  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 1131, in create_cursor\n    return self._dbapi_connection.cursor()\n  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 978, in cursor\n    return self.connection.cursor(*args, **kwargs)\nsqlalchemy.exc.ProgrammingError: (sqlite3.ProgrammingError) SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139631497549568 and this is thread id 139633173968640.\n[SQL: SELECT experiment.name AS experiment_name, experiment.time_created AS experiment_time_created, experiment.time_ended AS experiment_time_ended, experiment.git_hash AS experiment_git_hash, experiment.private AS experiment_private, experiment.experiment_filestore AS experiment_experiment_filestore \nFROM experiment \nWHERE experiment.name = ?]\n[parameters: [immutabledict({})]]\n(Background on this error at: http://sqlalche.me/e/f405)\n'}
Traceback (most recent call last):
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1173, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 775, in _init_compiled
    self.cursor = self.create_cursor()
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 1131, in create_cursor
    return self._dbapi_connection.cursor()
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 978, in cursor
    return self.connection.cursor(*args, **kwargs)
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139631497549568 and this is thread id 139633173968640.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/work/src/experiment/dispatcher.py", line 209, in <module>
    sys.exit(main())
  File "/work/src/experiment/dispatcher.py", line 194, in main
    raise error
  File "/work/src/experiment/dispatcher.py", line 191, in main
    dispatcher_main()
  File "/work/src/experiment/dispatcher.py", line 177, in dispatcher_main
    _record_experiment_time_ended(experiment.experiment_name)
  File "/work/src/experiment/dispatcher.py", line 76, in _record_experiment_time_ended
    models.Experiment.name == experiment_name).one()
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3347, in one
    ret = self.one_or_none()
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3316, in one_or_none
    ret = list(self)
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3389, in __iter__
    return self._execute_and_instances(context)
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3414, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1176, in _execute_context
    e, util.text_type(statement), parameters, None, None
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1173, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 775, in _init_compiled
    self.cursor = self.create_cursor()
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 1131, in create_cursor
    return self._dbapi_connection.cursor()
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 978, in cursor
    return self.connection.cursor(*args, **kwargs)
sqlalchemy.exc.ProgrammingError: (sqlite3.ProgrammingError) SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139631497549568 and this is thread id 139633173968640.
[SQL: SELECT experiment.name AS experiment_name, experiment.time_created AS experiment_time_created, experiment.time_ended AS experiment_time_ended, experiment.git_hash AS experiment_git_hash, experiment.private AS experiment_private, experiment.experiment_filestore AS experiment_experiment_filestore 
FROM experiment 
WHERE experiment.name = ?]
[parameters: [immutabledict({})]]
(Background on this error at: http://sqlalche.me/e/f405)
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 693, in _finalize_fairy
    fairy._reset(pool)
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 880, in _reset
    pool._dialect.do_rollback(self)
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 538, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139631497549568 and this is thread id 139633173968640.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x7efec3137730>
Traceback (most recent call last):
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 693, in _finalize_fairy
    fairy._reset(pool)
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 880, in _reset
    pool._dialect.do_rollback(self)
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 538, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139631497549568 and this is thread id 139633173968640.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 270, in _close_connection
    self._dialect.do_close(connection)
  File "/work/.venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 544, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139631497549568 and this is thread id 139633173968640.
```

@jonathanmetzman fyi, local setup mostly works, except this exception above.

**Comment by inferno-chromium** [comment]
Should be fixed now.
