### ISSUE TITLE
OSSFuzz benchmark integration doesn't work

### ISSUE THREAD

**Issue by mboehme** [google/fuzzbench#787]
I've been trying to integrate a recent regression in openssl. I followed [these](https://google.github.io/fuzzbench/developing-fuzzbench/adding-a-new-benchmark/#oss-fuzz-benchmarks-vs-standard-benchmarks) instructions, but I can't get the oss_fuzz_benchmark_integration.py script to work. 

I execute:
```bash
PYTHONPATH=. python3 benchmarks/oss_fuzz_benchmark_integration.py -p openssl \
  -f client -c 7b5108dff4cfde059ca278147a188fb6254603d1 -d 2020-02-20T16:58:19+00:00
```

First, it doesn't want to format a log message.

```python
Traceback (most recent call last):
  File "benchmarks/oss_fuzz_benchmark_integration.py", line 261, in <module>
    main()
  File "benchmarks/oss_fuzz_benchmark_integration.py", line 256, in main
    args.commit, args.date, args.oss_fuzz_corpus)
  File "benchmarks/oss_fuzz_benchmark_integration.py", line 217, in integrate_benchmark
    copy_oss_fuzz_files(project, commit_date, benchmark_dir)
  File "benchmarks/oss_fuzz_benchmark_integration.py", line 88, in copy_oss_fuzz_files
    projects_dir
  File "benchmarks/oss_fuzz_benchmark_integration.py", line 56, in git
    return new_process.execute(['git'] + cmd, cwd=self.repo_dir)
  File "/home/ubuntu/fuzzbench/common/new_process.py", line 123, in execute
    logs.error(log_message, extras=log_extras)
  File "/home/ubuntu/fuzzbench/common/logs.py", line 191, in error
    _report_error_with_retries(message % args)
TypeError: not enough arguments for format string
```

When I comment out that log_message, it complains about an "unknown revision or path not in the working tree". I fixed this by adding a `--` in front of projects_dir [here](https://github.com/google/fuzzbench/blob/master/benchmarks/oss_fuzz_benchmark_integration.py#L88):
```Python
 _, oss_fuzz_commit, _ = oss_fuzz_repo_manager.git([
            'log', '--before=' + commit_date.isoformat(), '-n1', '--format=%H',
            '--', projects_dir
        ])
```

 After that it complains about a missing directory (and restores the original `oss_fuzz_benchmark_integration.py` script).
```
WARNING:root:No suitable earlier OSS-Fuzz commit found.
WARNING:root:gcloud not found in PATH.
Traceback (most recent call last):
  File "benchmarks/oss_fuzz_benchmark_integration.py", line 261, in <module>
    main()
  File "benchmarks/oss_fuzz_benchmark_integration.py", line 256, in main
    args.commit, args.date, args.oss_fuzz_corpus)
  File "benchmarks/oss_fuzz_benchmark_integration.py", line 220, in integrate_benchmark
    benchmark_dir)
  File "benchmarks/oss_fuzz_benchmark_integration.py", line 204, in create_oss_fuzz_yaml
    yaml_utils.write(yaml_filename, config)
  File "/home/ubuntu/fuzzbench/common/yaml_utils.py", line 30, in write
    with open(yaml_filename, 'w') as file_handle:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/fuzzbench/benchmarks/openssl_client/benchmark.yaml'
```

When I manually create this directory and re-execute, I only get a benchmark.yaml file.

**Comment by inferno-chromium** [comment]
It succeeds for me. It looks like you are missing third_party/oss-fuzz folder
you need to do
`git submodule update --init`
as per https://google.github.io/fuzzbench/getting-started/prerequisites/#getting-the-code
we were thinking to remove this oss-fuzz code deps, sorry for confusion.

basically it tries
git log --before=2020-02-20T16:58:19+00:00 -n1 --format=%H <your-fuzzbench>/third_party/oss-fuzz/projects/openssl
and fails.

**Comment by mboehme** [comment]
Works! Sorry 😅. Thanks!
