### ISSUE TITLE
sqlalchemy.exc.OperationalError  no such column

### ISSUE THREAD

**Issue by RosenZhu** [google/fuzzbench#942]
When I try to build images, the build process has an error about sqlite3.OperationalError, and it only builds one image named gcr.io/fuzzbench/dispatcher-image. I'm wondering whether the error is related to the update from python 3.7 to python 3.8.
The error message is as follows:

```
INFO:root:Starting experiment.
ERROR:root:Error conducting experiment. Extras: {'traceback': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context\n    self.dialect.do_execute(\n  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute\n    cursor.execute(statement, parameters)\nsqlite3.OperationalError: no such column: experiment.description\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/work/src/experiment/dispatcher.py", line 192, in main\n    dispatcher_main()\n  File "/work/src/experiment/dispatcher.py", line 144, in dispatcher_main\n    _initialize_experiment_in_db(experiment.config)\n  File "/work/src/experiment/dispatcher.py", line 58, in _initialize_experiment_in_db\n    experiment_exists = db_utils.query(models.Experiment).filter(\n  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3402, in first\n    ret = list(self[0:1])\n  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3176, in __getitem__\n    return list(res)\n  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3508, in __iter__\n    return self._execute_and_instances(context)\n  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3533, in _execute_and_instances\n    result = conn.execute(querycontext.statement, self._params)\n  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute\n    return meth(self, multiparams, params)\n  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection\n    return connection._execute_clauseelement(self, multiparams, params)\n  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement\n    ret = self._execute_context(\n  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context\n    self._handle_dbapi_exception(\n  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception\n    util.raise_(\n  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_\n    raise exception\n  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context\n    self.dialect.do_execute(\n  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute\n    cursor.execute(statement, parameters)\nsqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: experiment.description\n[SQL: SELECT experiment.name AS experiment_name, experiment.time_created AS experiment_time_created, experiment.time_ended AS experiment_time_ended, experiment.git_hash AS experiment_git_hash, experiment.private AS experiment_private, experiment.experiment_filestore AS experiment_experiment_filestore, experiment.description AS experiment_description \nFROM experiment \nWHERE experiment.name = ?\n LIMIT ? OFFSET ?]\n[parameters: (\'testchurns\', 1, 0)]\n(Background on this error at: http://sqlalche.me/e/13/e3q8)\n'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: experiment.description

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/work/src/experiment/dispatcher.py", line 210, in <module>
    sys.exit(main())
  File "/work/src/experiment/dispatcher.py", line 195, in main
    raise error
  File "/work/src/experiment/dispatcher.py", line 192, in main
    dispatcher_main()
  File "/work/src/experiment/dispatcher.py", line 144, in dispatcher_main
    _initialize_experiment_in_db(experiment.config)
  File "/work/src/experiment/dispatcher.py", line 58, in _initialize_experiment_in_db
    experiment_exists = db_utils.query(models.Experiment).filter(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3402, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3176, in __getitem__
    return list(res)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3508, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3533, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: experiment.description
[SQL: SELECT experiment.name AS experiment_name, experiment.time_created AS experiment_time_created, experiment.time_ended AS experiment_time_ended, experiment.git_hash AS experiment_git_hash, experiment.private AS experiment_private, experiment.experiment_filestore AS experiment_experiment_filestore, experiment.description AS experiment_description 
FROM experiment 
WHERE experiment.name = ?
 LIMIT ? OFFSET ?]
[parameters: ('testchurns', 1, 0)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

**Comment by inferno-chromium** [comment]
Is this local experiment or experiment on cloud ?
your database is of old version, at the time when description column didnt exist. it does exist now.
you need to do run the last 2 commands to upgrade db - see https://google.github.io/fuzzbench/running-a-cloud-experiment/setting-up-a-google-cloud-project/#set-up-the-database
if using local db, just delete the file and it should then create from scratch.

**Comment by RosenZhu** [comment]
> Is this local experiment or experiment on cloud ?
> your database is of old version, at the time when description column didnt exist. it does exist now.
> you need to do run the last 2 commands to upgrade db - see https://google.github.io/fuzzbench/running-a-cloud-experiment/setting-up-a-google-cloud-project/#set-up-the-database
> if using local db, just delete the file and it should then create from scratch.

Thanks. I run experiments locally,  and after I delete the file fuzzbench-data/local.db, the build process succeeds.

**Comment by jonathanmetzman** [comment]
You might be able to avoid these issues in the future by running migrations instead of deleting the db.
